# Generated by Django 5.0 on 2024-01-05 06:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tasks",
            name="created_on",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
