# Generated by Django 5.0 on 2024-01-09 18:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0005_taskstatuses_alter_taskassignments_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taskassignments",
            name="status",
            field=models.CharField(
                choices=[
                    ("todo", "To Do"),
                    ("in_progress", "In Progress"),
                    ("completed", "Completed"),
                ],
                max_length=20,
            ),
        ),
        migrations.DeleteModel(
            name="TaskStatuses",
        ),
    ]
