# Generated by Django 5.0 on 2024-01-03 18:42

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="users",
            name="date_joined",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2024, 1, 3, 18, 42, 18, 981225, tzinfo=datetime.timezone.utc
                ),
                verbose_name="date joined",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="users",
            name="is_admin",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="users",
            name="last_login",
            field=models.DateTimeField(auto_now=True, verbose_name="last login"),
        ),
        migrations.AlterField(
            model_name="users",
            name="email",
            field=models.EmailField(max_length=60, unique=True, verbose_name="email"),
        ),
        migrations.AlterField(
            model_name="users",
            name="password",
            field=models.CharField(max_length=128, verbose_name="password"),
        ),
        migrations.AlterField(
            model_name="users",
            name="role",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="users.roles",
            ),
        ),
        migrations.AlterField(
            model_name="users",
            name="username",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
