# Generated by Django 5.0 on 2024-01-03 18:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_users_date_joined_users_is_admin_users_last_login_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="date_joined",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="date joined"
            ),
        ),
        migrations.AlterField(
            model_name="users",
            name="last_login",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="last login"
            ),
        ),
    ]
