# Generated by Django 5.0 on 2024-01-04 16:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_alter_users_date_joined_alter_users_last_login"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="users",
            name="role",
        ),
        migrations.DeleteModel(
            name="Roles",
        ),
        migrations.DeleteModel(
            name="Users",
        ),
    ]
